openapi: 3.0.1
info:
  title: Schema API Public Endpoints v1
  description: 'JSON Schema API is an internal tool designed to manage and validate JSON schemas used across our organization. It provides a centralized repository for storing, retrieving, and validating schemas, ensuring data consistency and adherence to defined structures.'
  version: v1
servers:
  - url: https://dev-api.raqn.io/schema/v1
paths:
  '/schemas/validate/{schemaName}':
    post:
      summary: Validate object against schema
      description: Validates an object against a schema by schema name
      operationId: validate_object_against_schema
      parameters:
        - name: schemaName
          in: path
          description: Schema name
          required: true
          schema:
            type: string
      requestBody:
        description: ''
        content:
          application/json:
            examples:
              default:
                summary: ''
                description: ''
                value:
                  age: 19
                  first_name: John
                  last_name: Doe
                externalValue: ''
      responses:
        '200':
          description: ''
        '400':
          description: ''
        '404':
          description: ''
        '500':
          description: ''
  '/schemas/{schemaName}':
    get:
      summary: Get JSON schema by schema name
      description: Get JSON schema by schema name
      operationId: get_schema_by_schema_name
      parameters:
        - name: schemaName
          in: path
          description: Schema name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
        '404':
          description: ''
        '500':
          description: ''
  /rfc7807:
    get:
      summary: Get API health status
      description: Get API health status
      operationId: get_rfc7807_schema
      responses:
        '200':
          description: ''
        '500':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]