openapi: 3.0.1
info:
  title: PSS API
  description: Product Status Service API documentation
  termsOfService: ''
  contact:
    name: ''
    url: ''
    email: info@henkel.de
  license:
    name: unlicensed
    url: ''
  version: 0.0.1
servers:
  - url: https://app-pss-restapi-uat.azurewebsites.net
    description: Generated server url
paths:
  /api/v1/products/variant/status:
    get:
      tags:
        - public-product-resource
      operationId: checkVariantProductStatus
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
        - name: catalogId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProductStatusDTO'
  /api/v1/products/base-product/status:
    get:
      tags:
        - public-product-resource
      operationId: checkBaseProductStatus
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
        - name: catalogId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProductStatusDTO'
  /api/v1/channels/{channelId}/variants:
    get:
      tags:
        - public-channel-resource
      operationId: getVariant
      parameters:
        - name: channelId
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Zero-based page index (0..N)
          required: false
          schema:
            minimum: 0
            type: integer
            default: 0
        - name: size
          in: query
          description: The size of the page to be returned
          required: false
          schema:
            minimum: 1
            type: integer
            default: 20
        - name: sort
          in: query
          description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
          required: false
          schema:
            type: array
            items:
              type: string
        - name: isRaw
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Variant'
  /api/v1/channels/{channelId}/variants/{idh}:
    get:
      tags:
        - public-channel-resource
      operationId: getVariants
      parameters:
        - name: channelId
          in: path
          required: true
          schema:
            type: string
        - name: idh
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Zero-based page index (0..N)
          required: false
          schema:
            minimum: 0
            type: integer
            default: 0
        - name: size
          in: query
          description: The size of the page to be returned
          required: false
          schema:
            minimum: 1
            type: integer
            default: 20
        - name: sort
          in: query
          description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
          required: false
          schema:
            type: array
            items:
              type: string
        - name: isRaw
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Variant'
  /api/v1/channels/{channelId}/products:
    get:
      tags:
        - public-channel-resource
      operationId: getProduct
      parameters:
        - name: channelId
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Zero-based page index (0..N)
          required: false
          schema:
            minimum: 0
            type: integer
            default: 0
        - name: size
          in: query
          description: The size of the page to be returned
          required: false
          schema:
            minimum: 1
            type: integer
            default: 20
        - name: sort
          in: query
          description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
          required: false
          schema:
            type: array
            items:
              type: string
        - name: isRaw
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BaseProduct'
  /api/v1/channels/{channelId}/products/{code}:
    get:
      tags:
        - public-channel-resource
      operationId: getProducts
      parameters:
        - name: channelId
          in: path
          required: true
          schema:
            type: string
        - name: code
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Zero-based page index (0..N)
          required: false
          schema:
            minimum: 0
            type: integer
            default: 0
        - name: size
          in: query
          description: The size of the page to be returned
          required: false
          schema:
            minimum: 1
            type: integer
            default: 20
        - name: sort
          in: query
          description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
          required: false
          schema:
            type: array
            items:
              type: string
        - name: isRaw
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BaseProduct'
components:
  schemas:
    ProductStatusDTO:
      type: object
      properties:
        input:
          type: object
          additionalProperties:
            type: string
        active:
          type: boolean
        activeChannels:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
    Variant:
      required:
        - active
        - channel
        - idh
      type: object
      properties:
        idh:
          maxLength: 2147483647
          minLength: 3
          type: string
        channel:
          maxLength: 2147483647
          minLength: 3
          type: string
        active:
          type: boolean
        activeNow:
          type: boolean
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        country:
          pattern: ^[A-Z]{2}$
          type: string
        reportedState:
          type: boolean
        pdhData:
          type: object
          additionalProperties:
            type: object
    BaseProduct:
      required:
        - active
        - channel
        - code
      type: object
      properties:
        code:
          maxLength: 2147483647
          minLength: 3
          type: string
        channel:
          maxLength: 2147483647
          minLength: 3
          type: string
        active:
          type: boolean
        activeNow:
          type: boolean
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        country:
          pattern: ^[A-Z]{2}$
          type: string
        reportedState:
          type: boolean
        pdhData:
          type: object
          additionalProperties:
            type: object
