openapi: 3.0.1
info:
  title: API for Taxonomy
  description: API for Taxonomy
  version: v1
servers:
  - url: https://dev-api.raqn.io/taxonomies/v1
paths:
  '/taxonomy/{taxonomyName}':
    post:
      summary: Create Taxonomy
      description: Creates a taxonomy with a given name and validates it against schema with the same name
      operationId: TaxonomyController_createTaxonomy
      parameters:
        - name: taxonomyName
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: ''
    get:
      summary: Get all taxonomies by schema name
      description: Get all taxonomies by schema name
      operationId: TaxonomyController_getTaxonomiesByName
      parameters:
        - name: taxonomyName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
  /taxonomy:
    get:
      summary: Get all taxonomies
      description: 'Get all taxonomies, could be paginated in the future'
      operationId: TaxonomyController_getTaxonomies
      responses:
        '200':
          description: ''
  '/taxonomy/{taxonomyName}/{id}':
    get:
      summary: Get single taxonomy
      description: Get single taxonomies by schema name and id
      operationId: TaxonomyController_getTaxonomy
      parameters:
        - name: taxonomyName
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
    put:
      summary: Update a taxonomy
      description: Update a specific taxonomy filtered by name and id
      operationId: TaxonomyController_updateTaxonomy
      parameters:
        - name: taxonomyName
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
    delete:
      summary: Delete a taxonomy
      description: Delete a specific taxonomy by name and id
      operationId: TaxonomyController_deleteTaxonomy
      parameters:
        - name: taxonomyName
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]